name: Build mipBook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIPBOOK_VERSION: 0.4.40

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout new repo
      uses: actions/checkout@v2

    - name: Install mipbook
      run: |
        mkdir mipbook
        curl -Lf https://github.com/rust-lang/mdBook/releases/download/v${{ env.MIPBOOK_VERSION }}/mdbook-v${{ env.MIPBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mipbook
        echo `pwd`/mipbook >> $GITHUB_PATH

    - name: Generate Book
      run: ./generate_book.sh

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book